# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f0af5e894418d1fc8e49bff85cd7047dd297ea41ed8c3954e45b05af848045774359f8d649c47a3b76bbe3a08f6e7df9e88773a507e7df67a9e92e6a6dc8f039

test:
  secret_key_base: 4bd8b096f881a45cfb97370432ef460a2fbb775c64a13ec691a2a839062b85b070ec043f80bf1b9ba1f6deab740b48190d0eb98f9b1d30e04d98eb80be2135d8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
